<?php $countries = $this->getCountryOptions(); ?>
<?php $shippingAddress = $this->getOrder()->getShippingAddress(); ?>

<div class="order-address" id="order-shipping_address_fields">
    <!-- <div class="order-save-in-address-book">
        <input name="same_as_biling" type="checkbox" id="same-as-biling" onclick="return disabledFields(this)" value="1" <?php //if ($shippingAddress->getSameAsBilling()) : ?>checked<?php //endif; ?>>
        <label for="same-as-biling">Same as Billing</label> &nbsp;&nbsp;&nbsp;&nbsp;
    </div> -->
    <div class="content">
        <div class="hor-scroll">
            <table cellspacing="0" class="form-list">
                <tbody>
                    <tr>
                        <td class="label"><label for="name">First Name <span class="required">*</span></label></td>
                        <td class="value"><?php echo $shippingAddress ->getFirstName() ?>
                            <!-- <input name="first_name" id="shipping_firstname" value="" class=" required-entry input-text required-entry" type="text"> -->
                        </td>
                    </tr>
                    <tr>
                        <td class="label"><label for="name">Last Name <span class="required">*</span></label></td>
                        <td class="value"><?php echo $shippingAddress ->getLastName() ?>
                            <!-- <input name="last_name" id="shipping_lastname" value="" class=" required-entry input-text required-entry" type="text"> -->
                        </td>
                    </tr>
                    <tr>
                        <td class="label"><label for="address">Address <span class="required">*</span></label></td>
                        <td class="value"><?php echo $shippingAddress->getAddress()  ?>
                            <!-- <div class="multi-input"><input id="shipping_address" name="address" value="" class="input-text required-entry" type="text"> -->
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td class="label"><label for="city">City <span class="required">*</span></label></td>
                        <td class="value"><?php echo $shippingAddress->getCity()  ?>
                            <!-- <input id="shipping_city" name="city" value="" class=" required-entry input-text required-entry" type="text"> -->
                        </td>
                    </tr>
                    <tr>
                        <td class="label"><label for="state">State <span class="required">*</span></label></td>
                        <td class="value"><?php echo $shippingAddress->getState()  ?>
                            <!-- <input id="shipping_state" name="state" value="" class=" required-entry input-text required-entry" type="text"> -->
                        </td>
                    </tr>
                    <tr>
                        <td class="label"><label for="zipcode">Zipcode <span class="required">*</span></label></td>
                        <td class="value"><?php echo $shippingAddress->getZipcode()  ?>
                            <!-- <input id="shipping_zipcode" name="zipcode" value="" class=" required-entry input-text required-entry" type="text"> -->
                        </td>
                    </tr>
                    <tr>
                        <td class="label"><label for="country_id">Country <span class="required">*</span></label></td>
                        <td class="value">
                            <?php foreach ($countries as $country) : ?>
                                <?php if($country['value'] == $shippingAddress->getCountry()){echo $country['label'];} ?>
                            <?php endforeach; ?>
                            <!-- <select id="shipping_country_id" name="country" class="required-entry required-entry select">
                                <?php //foreach ($countries as $country) : ?>
                                    <option value="<?php //echo $country['value'] ?>" <?php //if ($country['value'] == $shippingAddress->getCountry()) : ?>selected<?php //endif; ?>><?php echo $country['label'] ?></option>
                                <?php //endforeach; ?>
                            </select> -->
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <!-- <div class="order-save-in-address-book">
        <input name="save_in_shipping_address" type="checkbox" id="save-in-shipping-address-book" value="1">
        <label for="save-in-shipping-address-book">Save in address book</label>
    </div> -->


</div>