<div id="messageHtml"></div>
<div id="contentHtml">
<?php $cart = $this->getCart(); ?>
<div style="float: left">
    <h3><?php echo $this->getHeaderText(); ?></h3>
</div>

<div style="float: right">
<button title="Submit Order" type="button" class="scalable save" onclick="setLocation('<?php echo $this->getUrl('*/order/submitOrder', ['_current' => true]) ?>')"><span><span><span>Submit Order</span></span></span></button>
</div>
<br><br>
<div>
    <?php echo $this->getChildHtml('product'); ?>
</div>

<div>
    <?php echo $this->getChild('orderItems')->setCart($cart)->toHtml(); ?>
</div>

<div>
    <?php echo $this->getChild('accountInfo')->setCart($cart)->toHtml(); ?>
</div>

<div style=" display: flex; margin-top:20px;">
    <div style="margin-right:10px; width: 100%;">
        <?php echo $this->getChild('billingAddress')->setCart($cart)->toHtml(); ?>
    </div>
    <div style="margin-left:10px; width: 100%;">
        <?php echo $this->getChild('shippingAddress')->setCart($cart)->toHtml(); ?>
    </div>
</div>

<div style="width: 49%; float: left;">
    <?php echo $this->getChild('paymentMethod')->setCart($cart)->toHtml(); ?>
</div>

<div style="width: 49%; float: right;">
    <?php echo $this->getChild('shippingMethod')->setCart($cart)->toHtml(); ?>
</div>

<div>
    <?php echo $this->getChild('orderTotal')->setCart($cart)->toHtml(); ?>
</div>

</div>