<?php
$buttons = $this->getButtonsHtml();
$collection = $this->getCollection();
$columns = $this->getColumns();
//echo "<pre>";

?>

<div class="grid">
    <div class="hor-scroll">
        <table cellspacing="0" class="data">
            <?php foreach ($columns as $key => $column) : ?>
                <col width="<?php echo $column['width'] ?>" />
            <?php endforeach; ?>
                <col width="50" />
                <col width="50" />
            <thead>
                <tr class="headings">
                    <?php foreach ($columns as $key => $column) : ?>
                        <th><span class="nobr"><a href="#" name="<?php echo $key ?>" title="asc" class="not-sort"><span class="sort-title"><?php echo $column['header'] ?></span></a></span></th>
                    <?php endforeach; ?>
                    <th><span class="nobr">Total</span></th>
                    <th><span class="nobr">Delete</span></th>
                </tr>
            </thead>
            <tbody>
            <?php if($collection->getData()): ?>
            <?php foreach ($collection as $row): ?>
                <tr title="#">
                    <td class=" "> <?php echo $row->getName() ?> </td>
                    <td class=" "> <?php echo $row->getSku() ?> </td>
                    <td class=" "> <?php echo $row->getBasePrice() ?> </td>
                    <td class=" "> <input type="number" step="any" required min="1" required name="data[<?php echo $row->getId() ?>][price]" value="<?php echo $row->getPrice() ?>" class="input-text"> </td>
                    <td class="a-center "><input type="number" min="0" required required name="data[<?php echo $row->getId() ?>][quantity]" value="<?php echo $row->getQuantity() ?>" class="input-text"></td>
                    <td class=" "> <strong><?php echo ($row->getPrice()*$row->getQuantity()) ?> </strong></td>
                    <td class=" "><button title="Delete" type="button" class="scalable" onclick="setLocation('<?php echo $this->getUrl('*/*/deleteItem', ['item_id' => $row->getId()]) ?>')"><span>Delete</span></button></td>
                </tr>
            <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="7" class="empty-text a-center"><?php echo $this->helper('order')->__('No record found') ?></td>
                </tr>
            <?php endif; ?>
            </tbody>

        </table>
    </div>
</div>