<?php $order = $this->getOrder(); ?>
<?php //echo "<pre>"; print_r($this->getChild('accountInfoForm')->setOrder($order)->getOrder()); die; ?>
<div class="entry-edit">
<form action="<?php echo $this->getFormUrl() ?>" id="account_form" method="POST">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="entry-edit-head">
        <!-- <div style="float: right;"><button title="Save" type="submit" class="scalable save" ><span><span><span>Save</span></span></span></button></div> -->
        <h4 class="fieldset-legend <?php echo ($this->getHeaderCssClass()) ? $this->getHeaderCssClass().' icon-head' : '' ?>"><?php echo $this->getHeaderText() ?></h4>
    </div>
    <div class="fieldset">
    <div class="hor-scroll">
    <table cellspacing="0" class="form-list">
        <tbody>
            <tr>
                <td class="label"><label for="first_name">First Name <span class="required">*</span></label></td>
                <td class="value"><?php echo $order->getFirstName() ?>
                    <!-- <input id="name" name="first_name" value="<?php //echo $order->getFirstName() ?>" class="required-entry input-text required-entry" type="text" required/> -->
                </td>
            </tr>
            <tr>
                <td class="label"><label for="last_name">Last Name <span class="required">*</span></label></td>
                <td class="value"><?php echo $order->getLastName() ?>
                    <!-- <input id="name" name="last_name" value="<?php //echo $order->getLastName() ?>" class="required-entry input-text required-entry" type="text" required/> -->
                </td>
            </tr>
            <tr>
                <td class="label"><label for="email">Email <span class="required">*</span></label></td>
                <td class="value"><?php echo $order->getEmail() ?>
                    <!-- <input id="email" name="email" value="<?php //echo $order->getEmail() ?>" class="validate-email required-entry input-text required-entry" type="email" required /> -->
                </td>
            </tr>
        </tbody>
    </table>
    </div>
    </div>
</form>
</div>
