<?php $order = $this->getOrder(); ?>

<div class="entry-edit">
    <form action="<?php echo $this->getFormUrl() ?>" id="cart_item" method="POST">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <div class="entry-edit-head">
        <!-- <div style="float: right;"><button title="Update" type="button" class="scalable add" onclick="object.setForm(this).load()"><span><span><span>Update</span></span></span></button></div> -->
        <h4 class="fieldset-legend <?php echo ($this->getHeaderCssClass()) ? $this->getHeaderCssClass().' icon-head' : '' ?>"><?php echo $this->getHeaderText() ?></h4>
    </div>
    <div class="fieldset">
        <?php echo $this->getChild('orderItemsGrid')->setOrder($order)->toHtml(); ?>
    </div>
    </form>
</div>