<div class="entry-edit">
<form action="<?php echo $this->getFormUrl() ?>" id="shippingmethod_form" method="POST">
        <?php echo $this->getBlockHtml('formkey'); ?>
    <div class="entry-edit-head">
    <div style="float: right;"><!-- <button title="Save" type="button" class="scalable save" onclick="object.setForm(this).load()"><span><span><span>Save</span></span></span></button> --></div>
        <h4 class="fieldset-legend <?php echo ($this->getHeaderCssClass()) ? $this->getHeaderCssClass().' icon-head' : '' ?>"><?php echo $this->getHeaderText() ?></h4>
    </div>
    <div class="fieldset">
    <?php $shippingMethodTitle = $this->getShippingMethodTitle(); ?>
    <?php $shippingCode = $this->getOrder()->getShippingMethodCode(); ?>

    <div class="entry-edit">
        <span class="nowrap">
            <?php foreach ($shippingMethodTitle as $key => $value) : ?> 
                <?php if($value->getconfigData('price')){$data = $value->getconfigData('price');} else{ $data = 0.00; } ?>
                <?php if($shippingCode == $key): ?>
                <?php echo $value->getconfigData('title'). ' '; ?><strong>$<?php if($value->getconfigData('price')){echo $value->getconfigData('price');} else{ echo "0.00"; }?></strong><br>
                <?php endif; ?>
            <?php endforeach; ?>
        </span>
    </div>
    </div>
</form>
</div>