<div class="entry-edit">
<form id="billingaddress_form" action="<?php echo $this->getFormUrl() ?>" method="post">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <div class="entry-edit-head">
        <div style="float: right;"><button title="Save" id="billingaddress_form_submit" type="button" class="scalable save"  onclick="return checkBillingForm()"><span><span><span>Save</span></span></span></button></div>
        <h4 class="fieldset-legend <?php echo ($this->getHeaderCssClass()) ? $this->getHeaderCssClass().' icon-head' : '' ?>"><?php echo $this->getHeaderText() ?></h4>
    </div>
    <div class="fieldset">
        <?php echo $this->getChild('billingAddressForm')->setCart($this->getCart())->toHtml(); ?>
    </div>
</form>
</div>

<script type="text/javascript">
    function checkBillingForm() {
        flag = 0;
        var fields = document.getElementsByClassName('billing');
        for(var i=0;i < fields.length;i++){
            if(fields[i].value == "" || fields[i].value == undefined){
                alert("Please Fill " + fields[i].name + " value");
                flag = 1;
                return false;
            }
        }
        if (flag) {
            return false;
        } else {
            var button = document.getElementById('billingaddress_form_submit');
            object.setForm(button).load();
        }
    }
</script>