<div class="entry-edit">
<form action="<?php echo $this->getFormUrl() ?>" id="paymentmethod_form" method="POST">
        <?php echo $this->getBlockHtml('formkey'); ?>
    <div class="entry-edit-head">
    <div style="float: right;"><button title="Save" type="button" id="paymentmethod_form_submit" class="scalable save" onclick="checkPaymentMethodForm()"><span><span><span>Save</span></span></span></button></div>
        <h4 class="fieldset-legend <?php echo ($this->getHeaderCssClass()) ? $this->getHeaderCssClass().' icon-head' : '' ?>"><?php echo $this->getHeaderText() ?></h4>
    </div>
    <div class="fieldset">
        <?php echo $this->getChild('paymentMethodForm')->setCart($this->getCart())->toHtml(); ?>
    </div>
</form>
</div>

<script type="text/javascript">
    function checkPaymentMethodForm() {
        flag = 1;
        var fields = document.getElementsByClassName('paymentMethod');
        for (var i = 0; i < fields.length; i++) {
            if (fields[i].checked == true) {
                flag = 0;
                break;
            }
        }
        if (flag) {
            alert("Please Select Payment Method");
            return false;
        } else {
            var button = document.getElementById('paymentmethod_form_submit');
            object.setForm(button).load();
        }
    }
</script>