<div>
    <button id="add-product" title="Add Select Product to Order" type="button" class="scalable add" style="float: right;" onclick="showGrid(this)"><span><span><span>Show Product</span></span></span></button>
</div>
<div class="entry-edit">
    <div id="productgrid" style="display: none;">
    <div class="entry-edit-head">
        <div style="float: right;"><?php //echo $this->getButtonsHtml() ?></div>
        <h4 class="fieldset-legend <?php echo ($this->getHeaderCssClass()) ? $this->getHeaderCssClass().' icon-head' : '' ?>"><?php echo $this->getHeaderText() ?></h4>
    </div>
    <div class="fieldset">
        <?php echo $this->getChildHtml('productGrid', true, true) ?>
    </div>
    </div>
</div>

<script>
    function showGrid(button) {
        document.getElementById('productgrid').style.display = "block"; 
        button.style.display = "none"; 
    }
</script>